dataloader:
  data_name: cifar100
  batch_size: 128
model:
  model_name: resnet18
optimizer:
  opt_name: sam
  opt_hyperparameter:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.001
    rho: 0.1
scheduler:
  sch_name: cosine
  sch_hyperparameter:
    T_max: 200
trainer:
  epochs: 200
logging:
  framework_name: tensorboard